#!/bin/sh

cd mklinuximg-1.0.11.1

./mklinuximg \
    ../../../output/build/linux-custom/arch/sparc/boot/image \
    ../../../output/images/image.dsu \
    -tools ../../../output/host/usr/bin/sparc-unknown-linux-uclibc \
    -cmdline "console=ttyS0,38400 rootfs=/dev/ram0"
